Month.create(name: 'Abyssan', order:1)
Month.create(name: 'Orcanus', order:2)
Month.create(name: 'Corvus', order:3)
Month.create(name: 'The Revival Feast', order:4, number_of_days: 7)
Month.create(name: 'Rilifana', order:5)
Month.create(name: 'Sheelan', order:6)
Month.create(name: 'Sundar', order:7)
Month.create(name: 'Llora', order:8)
Month.create(name: 'Draveth', order:9)
Month.create(name: 'Baervan', order:10)
Month.create(name: 'Marecarum', order:11)
Month.create(name: 'Umber', order:12)
Month.create(name: 'Uldeth', order:13)
Event.create(day: 23, month: 3, year: 194, content: 'Today', public: false)
